# Contains the extra parameters needed to configure each FEM

# script location: path to the run script for the FEM.
#                  Relative paths are from the advanced_IM folder.
#                  Absolute paths also work
# timeout_threshold: the time(seconds) for each OpenSees call before getting killed.
#                    since each component is a separate call, this value is per-component-based.
#                    set to null if no timeout is needed.

Steel_MF_5Story:
  script_location: 'Models/Steel_MF_5Story/run.py'
  timeout_threshold: null
SAC_Steel_MF_3Story:
  script_location: 'Models/SAC_Steel_MF_3Story/run.py'
  timeout_threshold: null
SAC_Steel_MF_9Story:
  script_location: 'Models/SAC_Steel_MF_9Story/run.py'
  timeout_threshold: null
Spear_3D_Model:
  script_location: 'Models/Spear_3D_Model/run.py'
  timeout_threshold: null
ATC_Steel_SCBF_3Story:
  script_location: 'Models/ATC_Steel_SCBF_3Story/run.py'
  timeout_threshold: null
ATC_Steel_SCBF_6Story:
  script_location: 'Models/ATC_Steel_SCBF_6Story/run.py'
  timeout_threshold: null
ATC_Steel_SCBF_12Story:
  script_location: 'Models/ATC_Steel_SCBF_12Story/run.py'
  timeout_threshold: 21600
Taghavi_Miranda_2005:
  script_location: 'Models/Taghavi_Miranda_2005/run.py'
  timeout_threshold: null
Burks_Baker_2013:
  script_location: 'Models/Burks_Baker_2013/run.py'
  timeout_threshold: null
Haselton_RC_4Story:
  script_location: 'Models/Haselton_RC_4Story/run.py'
  timeout_threshold: null
Haselton_RC_12Story:
  script_location: 'Models/Haselton_RC_12Story/run.py'
  timeout_threshold: null
Haselton_RC_20Story:
  script_location: 'Models/Haselton_RC_20Story/run.py'
  timeout_threshold: null
SDOF_IMK:
  script_location: 'Models/SDOF_IMK/run.py'
  timeout_threshold: null